Repository bee-queue/bee-queue, pull requests merged in 2020-11, with the labels that each got.

#134 feat: support custom strategies on a queue
  README.md
  index.d.ts
  lib/job.js
  lib/queue.js
  test/queue-test.js
Labels: enhancement

#297 Ensure we don't call `unpack` with too many elements
  lib/lua/checkStalledJobs.lua
  test/queue-test.js
Labels: bug

#311 fix(types): fix typescript definitions errors
  index.d.ts
Labels: bug, bug:regression
